clear all;
clc;
%Simulink Variables
Fs = 440000;
T = 1/Fs;
order = 16;
ripple = 1;

G1dB = 0;
G1 = 10^(G1dB/10);

G2dB = 0;
G2 = 10^(G2dB/10);

G3dB = 0;
G3 = 10^(G3dB/10);

G4dB = 0;
G4 = 10^(G4dB/10);

G5dB = 0;
G5 = 10^(G5dB/10);

G6dB = 0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
G6 = 10^(G6dB/10);

G7dB = 0;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
G7 = 10^(G7dB/10);

G8dB = 0.89;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G8 = 10^(G8dB/10);

G9dB = 2.25;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G9 = 10^(G9dB/10);

G10dB = 3.99;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G10 = 10^(G10dB/10);

G11dB = 6.12;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G11 = 10^(G11dB/10);

G12dB = 8.8;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G12 = 10^(G12dB/10);

G13dB = 11.98;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G13 = 10^(G13dB/10);

G14dB = 15.13;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G14 = 10^(G14dB/10);

G15dB = 18.39;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G15 = 10^(G15dB/10);

G16dB = 21.98;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G16 = 10^(G16dB/10);

G17dB = 23.9;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G17 = 10^(G17dB/10);

G18dB = 23.68;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G18 = 10^(G18dB/10);

G19dB = 22.83;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G19 = 10^(G19dB/10);

G20dB = 22.01;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G20 = 10^(G20dB/10);

G21dB = 21.59;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G21 = 10^(G21dB/10);

G22dB = 21.21;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G22 = 10^(G22dB/10);

G23dB = 21.01;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G8 = 10^(G8dB/10);

G24dB = 21;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G24 = 10^(G24dB/10);

G25dB = 21;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G25 = 10^(G25dB/10);

G26dB = 21;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
G26 = 10^(G26dB/10);

GdBansi = 30;
Gansi = 10^(GdBansi/10);