%% Test to see the performance of different FIR Windows 
Fh = 8000;
T = 1/(2*Fh);
Fs = 1/T;
order = 30;

vbf = dsp.VariableBandwidthFIRFilter('SampleRate', Fs, ...  
                                     'FilterType', 'BandPass', ... 
                                     'FilterORder', order, ...
                                     'Window', 'Hann', ...
                                     'CenterFrequency', )